export const MESSAGE_CHECK_XIAOHONGSHU_LOGIN = "BROWSER_CORE_CLAW_XIAOHONGSHU_CHECK_LOGIN";
export const MESSAGE_OPEN_XIAOHONGSHU_LOGIN = "BROWSER_CORE_CLAW_XIAOHONGSHU_OPEN_LOGIN";
export const MESSAGE_CAPTURE_XIAOHONGSHU_KEYWORD = "BROWSER_CORE_CLAW_XIAOHONGSHU_KEYWORD_CAPTURE";
export const MESSAGE_STOP_XIAOHONGSHU_KEYWORD = "BROWSER_CORE_CLAW_XIAOHONGSHU_KEYWORD_STOP";

export const XIAOHONGSHU_HOME_URL = "https://www.xiaohongshu.com/";
export const XIAOHONGSHU_READY_TIMEOUT_MS = 15000;
export const XIAOHONGSHU_FILTER_SETTLE_TIMEOUT_MS = 12000;
export const XIAOHONGSHU_FILTER_SETTLE_MIN_MS = 1800;
export const XIAOHONGSHU_FILTER_SETTLE_POLLS = 4;
