export const MESSAGE_CAPTURE_WEIBO_POST_DETAIL = "BROWSER_CORE_CLAW_WEIBO_POST_DETAIL_CAPTURE";
export const MESSAGE_STOP_WEIBO_POST_DETAIL = "BROWSER_CORE_CLAW_WEIBO_POST_DETAIL_STOP";
export const WEIBO_DETAIL_READY_TIMEOUT_MS = 25000;
export const WEIBO_DETAIL_SETTLE_MIN_MS = 900;
export const WEIBO_DETAIL_SETTLE_POLLS = 3;
