export const MESSAGE_CAPTURE_XIAOHONGSHU_PROFILE_INFO = "BROWSER_CORE_CLAW_XIAOHONGSHU_PROFILE_INFO_CAPTURE";
export const MESSAGE_STOP_XIAOHONGSHU_PROFILE_INFO = "BROWSER_CORE_CLAW_XIAOHONGSHU_PROFILE_INFO_STOP";

export const XIAOHONGSHU_HOME_URL = "https://www.xiaohongshu.com/";
export const XIAOHONGSHU_PROFILE_INFO_READY_TIMEOUT_MS = 20000;
export const XIAOHONGSHU_PROFILE_INFO_SETTLE_TIMEOUT_MS = 8000;
export const XIAOHONGSHU_PROFILE_INFO_SETTLE_MIN_MS = 900;
export const XIAOHONGSHU_PROFILE_INFO_SETTLE_POLLS = 3;
