export const MESSAGE_CAPTURE_XIAOHONGSHU_PROFILE = "BROWSER_CORE_CLAW_XIAOHONGSHU_PROFILE_CAPTURE";
export const MESSAGE_STOP_XIAOHONGSHU_PROFILE = "BROWSER_CORE_CLAW_XIAOHONGSHU_PROFILE_STOP";

export const XIAOHONGSHU_HOME_URL = "https://www.xiaohongshu.com/";
export const XIAOHONGSHU_PROFILE_READY_TIMEOUT_MS = 20000;
export const XIAOHONGSHU_PROFILE_SETTLE_TIMEOUT_MS = 12000;
export const XIAOHONGSHU_PROFILE_SETTLE_MIN_MS = 1200;
export const XIAOHONGSHU_PROFILE_SETTLE_POLLS = 3;
