export const MESSAGE_CAPTURE_XIAOHONGSHU_POST_DETAIL = "BROWSER_CORE_CLAW_XIAOHONGSHU_POST_DETAIL_CAPTURE";
export const MESSAGE_STOP_XIAOHONGSHU_POST_DETAIL = "BROWSER_CORE_CLAW_XIAOHONGSHU_POST_DETAIL_STOP";

export const XIAOHONGSHU_POST_DETAIL_HOME_URL = "https://www.xiaohongshu.com/";
export const XIAOHONGSHU_POST_DETAIL_READY_TIMEOUT_MS = 25000;
export const XIAOHONGSHU_POST_DETAIL_SETTLE_MIN_MS = 900;
export const XIAOHONGSHU_POST_DETAIL_SETTLE_POLLS = 3;
