export const MESSAGE_CAPTURE_GOOGLE_NEWS = "BROWSER_CORE_CLAW_GOOGLE_NEWS_CAPTURE";
export const MESSAGE_STOP_GOOGLE_NEWS = "BROWSER_CORE_CLAW_GOOGLE_NEWS_STOP";
export const GOOGLE_NEWS_READY_TIMEOUT_MS = 25000;
