export const MESSAGE_CAPTURE_WEIBO_PROFILE_POSTS = "BROWSER_CORE_CLAW_WEIBO_PROFILE_POSTS_CAPTURE";
export const MESSAGE_STOP_WEIBO_PROFILE_POSTS = "BROWSER_CORE_CLAW_WEIBO_PROFILE_POSTS_STOP";
export const WEIBO_HOME_URL = "https://weibo.com/";
export const WEIBO_PROFILE_READY_TIMEOUT_MS = 25000;
export const WEIBO_PROFILE_SETTLE_MIN_MS = 900;
export const WEIBO_PROFILE_SETTLE_POLLS = 3;
